version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
    environment:
      - NAME=Dhini

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NAME=Dhini

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - frontend
      - backend
